"""extend course table and add chapter table

Revision ID: fffbecb6fd74
Revises: f514b4d8015f
Create Date: 2020-09-13 15:16:45.993576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fffbecb6fd74'
down_revision = 'f514b4d8015f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('description', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'description')
    # ### end Alembic commands ###
